global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'dynamic-form-manager'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['dynamic-form-manager:8080']
        labels:
          application: 'Dynamic Form Manager Application'