spring:
  application:
    name: dynamic-form-manager
  jpa:
    generate-ddl: true  #Generate DDL for the database schema
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/finclutech_db} # Default MySQL URL
    username: ${MYSQL_USER:admin} # Default MySQL username
    password: ${MYSQL_PASSWORD:admin@2025} # Default MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC driver
    hikari:
      maximum-pool-size: 10 # Maximum number of connections in the pool
      minimum-idle: 5 # Minimum number of idle connections
      idle-timeout: 30000 # Timeout for idle connections (in ms)
      max-lifetime: 1800000 # Maximum lifetime of a connection (in ms)
      connection-timeout: 20000 # Timeout for getting a connection (in ms)
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/submissions_db} # Default MongoDB URI
  sql:
    init:
      mode: always # Initialize SQL scripts on startup

logging:
  level:
    org.hibernate.SQL: WARN # Log only warnings for SQL queries
    org.springframework.data.mongodb.core.MongoTemplate: WARN # Log only warnings for MongoDB queries
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${SERVER_PORT:8080} # Default Spring Boot application port

jwt:
  secret: "6a8e1e15d6b7892e8e6f13d7bc54b6c07d398c57923c8b2044973203e7023704" # TODO: Get it from vault
  expirationTime: 86400000
  tokenPrefix: 'Bearer '
  authorizationHeaderString: Authorization
  headerSkipLength: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: "http://tempo:9411/api/v2/spans"
  endpoint:
    health:
      show:
        details: "always"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0


