name: CI/CD Pipeline

on:
  push: # Trigger the workflow on every push
    branches:
      - '**' # This ensures the workflow runs on all branches
  pull_request: # Trigger the workflow on pull requests
    branches:
      - main # This ensures the workflow runs on pull requests to all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for backend
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test the backend
      - name: Build and test backend
        run: |
          cd backend
          ./mvnw clean install
          ./mvnw test

      # Step 5: Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 6: Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 7: Build and test the frontend
      - name: Build and test frontend
        run: |
          cd ui
          npm install
          npm run build
          npm test

      # Step 8: Run Cucumber tests
      - name: Run Cucumber tests
        run: |
          cd backend
          ./mvnw test -Dcucumber.options="--plugin pretty"

      # Step 9: Install Docker Compose and Build Docker images
      - name: Install Docker Compose and Build Docker images
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose -f backend/docker-compose.yml build